FROM php
RUN apt-get update

#RUN php -r "readfile('http://getcomposer.org/installer');"| php -- --install-dir=/usr/bin/--filename=composer

#COPY default.conf /etc/apache2/sites-enabled/000-default.conf

#WORKDIR /var/www/app

CMD ["echo","hello"]

